import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import "bootstrap/dist/css/bootstrap.min.css";
import { LandingPageLayout } from "@/layout";
import { AboutSection, ContactSection, FAQSection, HeroSection, PricingSection, ProcessSection, ServicesSection, TestimonySection } from "@/components";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {

  return (
    <>
      <Head>
        <title>Carlovers</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link href="/public/assets/css/style.css" rel="stylesheet" />


      </Head>
      <LandingPageLayout>
        <HeroSection />
        <main id="main" className={`${styles.main} ${inter.className}`}>
          <AboutSection />
          <ServicesSection />
          <ProcessSection />
          <TestimonySection />
          <PricingSection />
          {/* ------------------------------------------------------------------- */}
          {/* <GoogleAdSenseComponent/> */}
          <FAQSection />
          <ContactSection />
        </main>
      </LandingPageLayout>
    </>
  );
}
